apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: transaction-svc-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transaction-svc
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
