apiVersion: v1
kind: Service
metadata:
  name: limite-svc
  labels:
    app: limite-svc
    service: limite-svc
spec:
  ports:
    - port: 8081
      name: http
  selector:
    app: limite-svc
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-limite-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: limite-svc
  labels:
    app: limite-svc
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: limite-svc
      version: v1
  template:
    metadata:
      labels:
        app: limite-svc
        version: v1
    spec:
      serviceAccountName: sa-limite-svc
      containers:
        - name: limite-svc
          image: i9developement/limite-svc:0.4.1-SNAPHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /actuator/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 90
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /actuator/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 80
