apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-bff
data:
  application.properties: |-
    spring.kafka.bootstrap-servers=35.223.152.223:9092
    spring.security.oauth2.resourceserver.jwt.issuer-uri=https://keycloak.i9developement.com.br/auth/realms/i9developement
    spring.redis.host=localhost
    spring.redis.port=6379
    spring.zipkin.base-url=localhost:9411
    app.urlTransaction=http://transaction-svc:8083/v1/transactions/block?agencia=%d&conta=%d
    app.urlTransactionById=http://transaction-svc:8083/v1/transactions/%s
    spring.security.oauth2.resourceserver.jwt.issuer-uri=localhost:8080/auth/realms/i9developement
