apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "jwt"
spec:
  targets:
  - name: transaction-bff
  origins:
  - jwt:
      issuer: "localhost:8080/auth/realms/i9developement"
      jwksUri: "localhost:8080/auth/realms/i9developement/protocol/openid-connect/certs"
  principalBinding: USE_ORIGIN

